(function () {
var g = [
  ['3-2-1-1-0', 'Backup rule: 3 copies, 2 media, 1 off-site, 1 offline/immutable, 0 errors after restore testing.', 'm5'],
  ['Account takeover (ATO)', 'An attacker gains control of a legitimate user account, often via phishing, MFA fatigue or a stolen session token.', 'm2'],
  ['Adversary-in-the-middle (AiTM)', 'Phishing that proxies the real login page to capture both the password and the session cookie, bypassing many MFA methods.', 'm2'],
  ['Alert fatigue', 'Desensitisation caused by high volumes of low-value alerts, leading analysts to miss real threats.', 'm4'],
  ['API', 'Application Programming Interface: a defined way for software to request data or actions from another system.', 'm8'],
  ['ARR / MRR', 'Annual / monthly recurring revenue: the predictable subscription income at the heart of an MSSP.', 'm3'],
  ['Assume breach', 'Zero trust principle: design and monitor as if an attacker is already inside.', 'm2'],
  ['Audit trail', 'A tamper-evident record of who did what, when and why.', 'm6'],
  ['BEC', 'Business Email Compromise: email-based fraud (often invoice or payroll redirection) that frequently uses no malware.', 'm2'],
  ['Benign positive', 'An alert where the detection worked correctly but the activity was expected or authorised.', 'm4'],
  ['CIA triad', 'Confidentiality, integrity and availability: the three core properties security protects.', 'm2'],
  ['CIS Controls', 'Center for Internet Security\'s 18 prioritised safeguards (v8), grouped into Implementation Groups IG1–IG3.', 'm6'],
  ['Client credentials flow', 'OAuth 2.0 flow where an application authenticates as itself (not a user) to obtain an access token.', 'm8'],
  ['Conditional Access', 'Microsoft Entra ID policies that grant, block or challenge sign-ins based on conditions such as location, device and risk.', 'm2'],
  ['Containment', 'Incident response step that stops a threat spreading, for example isolating a device or disabling an account.', 'm4'],
  ['Context window', 'The maximum amount of text (in tokens) an LLM can consider in one request.', 'm7'],
  ['Controller / processor', 'GDPR roles: the controller decides why and how data is processed; the processor processes it on the controller\'s behalf. POPIA equivalents: responsible party / operator.', 'm6'],
  ['Cyber Essentials', 'UK government-backed scheme with five controls: firewalls, secure configuration, security update management, user access control, malware protection.', 'm6'],
  ['Cyber Kill Chain', 'Lockheed Martin model of seven attack stages from reconnaissance to actions on objectives.', 'm2'],
  ['Cyber resilience', 'The ability to anticipate, withstand, detect, respond to and recover from cyber attacks, not only prevent them.', 'm1'],
  ['Dead-letter queue', 'A holding place for messages or jobs that repeatedly fail, so humans can inspect them.', 'm8'],
  ['Deception technology', 'Decoy assets (honeypots, honeytokens, canary files) that generate high-confidence alerts when touched.', 'm5'],
  ['Defanging', 'Altering indicators (hxxp, [.]) so they cannot be clicked or auto-linked when shared.', 'm9'],
  ['Defence in depth', 'Layering multiple independent controls so one failure does not lead to compromise.', 'm2'],
  ['DKIM', 'DomainKeys Identified Mail: a cryptographic signature proving a message was signed by a domain and unaltered.', 'm2'],
  ['DLP', 'Data Loss Prevention: controls that detect or block sensitive data leaving the organisation.', 'm5'],
  ['DMARC', 'Policy that requires SPF or DKIM to pass in alignment with the visible From domain and tells receivers what to do on failure (none, quarantine, reject).', 'm2'],
  ['Double extortion', 'Ransomware tactic: steal data, then encrypt it, threatening to leak it if the ransom is not paid.', 'm2'],
  ['DTEX', 'Insider risk management vendor partnered with J2, using behavioural endpoint telemetry with privacy features such as pseudonymisation.', 'm5'],
  ['EDR', 'Endpoint Detection and Response: records endpoint behaviour, detects threats and enables response such as isolation.', 'm5'],
  ['Embeddings', 'Numeric vector representations of text used for semantic search and clustering.', 'm7'],
  ['Enrichment', 'Adding context (user, asset, IP reputation, history) to an alert so it can be judged quickly.', 'm4'],
  ['Entra ID', 'Microsoft\'s cloud identity service (formerly Azure Active Directory).', 'm2'],
  ['Excessive agency', 'OWASP LLM risk: an AI system given more tools, permissions or autonomy than it needs.', 'm7'],
  ['False positive', 'An alert raised when no real threat exists, due to faulty logic or data.', 'm4'],
  ['GDAP', 'Granular Delegated Admin Privileges: Microsoft\'s time-bound, role-scoped model for partners administering customer tenants.', 'm8'],
  ['Golden dataset', 'A curated set of examples with known correct answers, used to evaluate AI or automation changes.', 'm7'],
  ['Honeytoken', 'A fake credential, record or file that should never be used; any use signals compromise.', 'm5'],
  ['Idempotency', 'Property where repeating an operation has the same effect as doing it once.', 'm8'],
  ['Immutable backup', 'A backup that cannot be modified or deleted for a set period, even by administrators.', 'm5'],
  ['Incident', 'A confirmed or suspected security event requiring response, often grouping several alerts.', 'm4'],
  ['Information Regulator', 'South Africa\'s regulator for POPIA and PAIA.', 'm6'],
  ['IOC', 'Indicator of Compromise: an observable artefact (IP, domain, hash, URL) associated with malicious activity.', 'm9'],
  ['iPaaS', 'Integration Platform as a Service: tools like Power Automate, Logic Apps, n8n, Make or Zapier for building integrations.', 'm8'],
  ['IRONSCALES', 'API-based email security platform using AI and crowdsourced user reports; a J2 partner.', 'm5'],
  ['ISO/IEC 27001', 'International standard for an information security management system; the 2022 Annex A lists 93 controls.', 'm6'],
  ['Isolation (device)', 'Cutting an endpoint off the network except for its security agent, to stop spread.', 'm5'],
  ['KQL', 'Kusto Query Language: the read-only pipe-based query language of Microsoft Sentinel, Defender and Log Analytics.', 'm9'],
  ['Lateral movement', 'Attacker moving from one compromised system to others inside a network.', 'm2'],
  ['Least privilege', 'Granting only the minimum access needed for a task, for the minimum time.', 'm2'],
  ['LOLBins', 'Living-off-the-land binaries: legitimate system tools abused by attackers to avoid detection.', 'm5'],
  ['MCP', 'Model Context Protocol: an open standard for connecting AI applications to tools and data sources.', 'm7'],
  ['MDR', 'Managed Detection and Response: a service combining 24/7 detection with hands-on response.', 'm3'],
  ['MFA fatigue', 'Attack that spams push MFA prompts until a user approves one.', 'm2'],
  ['Mimecast', 'Email security vendor known for its secure email gateway, archiving, continuity and awareness training; a J2 partner.', 'm5'],
  ['MITRE ATT&CK', 'Public knowledge base of adversary tactics and techniques; Enterprise has 14 tactics.', 'm2'],
  ['MSSP', 'Managed Security Service Provider: runs security monitoring and services for clients.', 'm3'],
  ['MTTA', 'Mean time to acknowledge: from alert creation to an analyst picking it up.', 'm4'],
  ['MTTD', 'Mean time to detect: from the start of malicious activity to an alert.', 'm4'],
  ['MTTR', 'Mean time to respond or resolve (define which): from alert to containment or closure.', 'm4'],
  ['NIST CSF 2.0', 'NIST Cybersecurity Framework 2.0 (2024) with six functions: Govern, Identify, Protect, Detect, Respond, Recover.', 'm1'],
  ['OWASP LLM Top 10', 'OWASP\'s list of the most critical risks for LLM applications, led by prompt injection.', 'm7'],
  ['Pagination', 'Splitting large API results into pages that must be followed with next links or cursors.', 'm8'],
  ['Phishing', 'Deceptive messages designed to trick recipients into revealing credentials, paying money or running malware.', 'm2'],
  ['Playbook', 'A documented, often automated, sequence of steps for handling a type of alert or incident.', 'm4'],
  ['POPIA', 'South Africa\'s Protection of Personal Information Act (Act 4 of 2013), enforceable from 1 July 2021, with eight conditions for lawful processing.', 'm6'],
  ['Precision', 'Of the items flagged positive, the share that truly were positive.', 'm7'],
  ['Prompt injection', 'Attack where untrusted input contains instructions that manipulate an LLM\'s behaviour.', 'm7'],
  ['PSA', 'Professional Services Automation: ticketing, contracts, time and billing system used by MSPs and MSSPs.', 'm8'],
  ['QBR', 'Quarterly Business Review: a regular client meeting reviewing service performance, risks and plans.', 'm3'],
  ['RAG', 'Retrieval-Augmented Generation: retrieving relevant documents and adding them to an LLM prompt for grounded answers.', 'm7'],
  ['Ransomware-as-a-Service', 'Criminal model where ransomware developers lease their tooling to affiliates for a share of profits.', 'm2'],
  ['Recall', 'Of the truly positive items, the share that were flagged.', 'm7'],
  ['Revenue leakage', 'Services delivered but not billed, for example seats added without contract updates.', 'm3'],
  ['RPO', 'Recovery Point Objective: maximum acceptable data loss measured in time.', 'm5'],
  ['RTO', 'Recovery Time Objective: maximum acceptable downtime before recovery.', 'm5'],
  ['SEG', 'Secure Email Gateway: filters email in-line before it reaches the mailbox (via MX records).', 'm5'],
  ['Service principal', 'An identity for an application in Entra ID, used by automations to access resources.', 'm8'],
  ['Shadow mode', 'Running an AI or automation that records its decisions without acting, to compare against humans.', 'm7'],
  ['SIEM', 'Security Information and Event Management: collects, correlates and searches logs; runs detection rules.', 'm4'],
  ['SLA', 'Service Level Agreement: contracted performance targets such as time to respond.', 'm3'],
  ['SOAR', 'Security Orchestration, Automation and Response: platforms that run automated response playbooks.', 'm4'],
  ['SOC', 'Security Operations Centre: the team and tooling that monitor and respond to threats, 24/7 at J2.', 'm4'],
  ['Source of truth', 'The single system designated as authoritative for a given piece of data.', 'm8'],
  ['SPF', 'Sender Policy Framework: DNS record listing servers allowed to send mail for a domain (checked against the envelope sender).', 'm2'],
  ['Structured output', 'LLM output constrained to a machine-readable format such as JSON matching a schema.', 'm7'],
  ['Supply chain attack', 'Compromising a trusted supplier (such as an MSP or MSSP) to reach its customers.', 'm2'],
  ['Tenant', 'An isolated instance of a cloud service for one organisation, such as a Microsoft 365 tenant.', 'm8'],
  ['Threat hunting', 'Proactively searching for attackers that evaded existing detections.', 'm4'],
  ['Token (LLM)', 'A chunk of text (roughly three-quarters of a word) that models process and bill by.', 'm7'],
  ['Triage', 'Rapid assessment of an alert to decide whether and how urgently to act.', 'm4'],
  ['True positive', 'An alert correctly identifying real malicious activity.', 'm4'],
  ['UK GDPR', 'The UK\'s retained version of the GDPR, alongside the Data Protection Act 2018; breaches reportable to the ICO within 72 hours.', 'm6'],
  ['Webhook', 'An HTTP callback a system sends to notify another of an event.', 'm8'],
  ['XDR', 'Extended Detection and Response: correlates endpoint, identity, email, cloud and network signals.', 'm5'],
  ['Zero trust', 'Security model built on verify explicitly, least privilege and assume breach.', 'm2']
];
g.forEach(function (row) {
  COURSE.glossary.push({ id: row[0].toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), term: row[0], def: row[1], module: row[2] });
});
})();
