(function () {
var g = [
  ['Account takeover', 'An attacker controls a real user\'s account, often their Microsoft 365 email.', 'm2'],
  ['Alert', 'An automatic warning that something might be wrong.', 'm3'],
  ['Alert fatigue', 'When too many false alarms make people miss real ones.', 'm3'],
  ['Archiving', 'Storing emails safely so they can be found later, e.g. for legal reasons.', 'm4'],
  ['Backup', 'A safe copy of data, used to recover after loss or ransomware.', 'm4'],
  ['BEC', 'Business Email Compromise: fraud using a real or fake business email account.', 'm4'],
  ['Breach', 'When an attacker gets in, or data gets out.', 'm2'],
  ['Business continuity', 'Keeping the business running during and after a problem.', 'm5'],
  ['CEO impersonation', 'Pretending to be the boss to rush staff into paying or sharing.', 'm4'],
  ['CIA triad', 'Confidentiality, integrity, availability: the three things security protects.', 'm2'],
  ['Compliance', 'Following the laws and standards that apply to you.', 'm5'],
  ['Contain', 'Stop an attack from spreading, e.g. isolate a laptop or lock an account.', 'm3'],
  ['Credentials', 'Username plus password.', 'm2'],
  ['Cyber resilience', 'Seeing attacks fast, responding, and recovering so the business keeps running.', 'm1'],
  ['Defence in depth', 'Several layers of protection that back each other up.', 'm2'],
  ['DLP', 'Data Loss Prevention: stopping data leaving where it should not.', 'm4'],
  ['DMARC', 'A setting on an email domain that stops others sending email pretending to be you.', 'm4'],
  ['Domain', 'The part after @ in an email address, e.g. company.co.za.', 'm4'],
  ['Double extortion', 'Ransomware gangs lock files and also threaten to publish stolen data.', 'm2'],
  ['DTEX', 'J2 partner for insider risk and behavioural data loss prevention.', 'm5'],
  ['Encryption', 'Scrambling data so only people with the key can read it.', 'm4'],
  ['Endpoint', 'A user\'s device: laptop, desktop, phone or server.', 'm4'],
  ['False positive', 'An alert that turns out to be harmless.', 'm3'],
  ['Honeypot', 'A decoy system. Any touch means an attacker, so alerts are very reliable.', 'm4'],
  ['Incident', 'A confirmed security problem that needs action.', 'm3'],
  ['Insider threat', 'Risk from someone inside the organisation, on purpose or by accident.', 'm2'],
  ['IRONSCALES', 'J2 partner: AI email security inside the mailbox, using user reports to catch phishing.', 'm5'],
  ['ISO 27001', 'International, certifiable standard for managing information security.', 'm5'],
  ['Least privilege', 'Giving people only the access they need, nothing more.', 'm2'],
  ['Maturity level', 'How advanced an organisation\'s security already is.', 'm1'],
  ['MDR', 'Managed Detection and Response: a team that finds and stops attacks for you, 24/7.', 'm3'],
  ['MFA', 'Multi-factor authentication: a second proof of identity as well as the password.', 'm2'],
  ['Microsoft 365', 'Microsoft\'s cloud email and office apps: Outlook, Teams, OneDrive, SharePoint.', 'm2'],
  ['Mimecast', 'J2 partner: email security gateway, archiving, continuity and awareness training.', 'm5'],
  ['MSP', 'Managed Service Provider: runs a company\'s IT.', 'm3'],
  ['MSSP', 'Managed Security Service Provider: runs a company\'s security as a monthly service.', 'm1'],
  ['Onboarding', 'Setting up a new client so the service can start.', 'm3'],
  ['Patch', 'A software update that fixes a weakness.', 'm4'],
  ['Perimeter', 'The edge of what you protect. For J2, "wherever your user is".', 'm2'],
  ['Phishing', 'Fake messages that trick people into clicking, opening files or giving passwords.', 'm2'],
  ['POPIA', 'South Africa\'s Protection of Personal Information Act, enforced by the Information Regulator.', 'm5'],
  ['Ransomware', 'Malware that locks files until a ransom is paid.', 'm2'],
  ['Recurring revenue', 'Income that repeats every month or year, e.g. subscriptions.', 'm3'],
  ['Security posture', 'The overall strength of an organisation\'s security right now.', 'm5'],
  ['SOC', 'Security Operations Centre: the 24/7 team that watches for and responds to attacks.', 'm1'],
  ['Social engineering', 'Manipulating people instead of hacking computers.', 'm2'],
  ['Triage', 'Quickly deciding how serious an alert is.', 'm3'],
  ['UK GDPR', 'UK data protection law. Serious breaches reported to the ICO within 72 hours.', 'm5'],
  ['Upsell', 'An existing client buying more services.', 'm3'],
  ['Visibility', 'Being able to see what is happening in systems and user behaviour.', 'm1'],
  ['Vulnerability', 'A weakness an attacker can use.', 'm4'],
  ['Zero trust', 'Never trust automatically; always verify every user and device.', 'm2']
];
g.forEach(function (row) {
  COURSE.glossary.push({ id: row[0].toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), term: row[0], def: row[1], module: row[2] });
});
})();
